name: "Copilot Setup Steps"

# This workflow sets up the development environment for GitHub Copilot Coding Agent.
# It uses a shared composite action to ensure environment consistency with CI/CD pipelines.
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
      - .github/actions/setup-powerbi-environment/**
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml
      - .github/actions/setup-powerbi-environment/**

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    
    # Use copilot environment for secrets and variables
    environment: copilot

    # Minimal permissions needed for setup
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PowerBI MCP Environment
        uses: ./.github/actions/setup-powerbi-environment
        with:
          python-version: "3.11"
          install-mode: "user"  # User installation for Copilot environment
          environment-type: "copilot"
          # Pass secrets and variables as inputs
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          default-tenant-id: ${{ secrets.DEFAULT_TENANT_ID }}
          default-client-id: ${{ secrets.DEFAULT_CLIENT_ID }}
          default-client-secret: ${{ secrets.DEFAULT_CLIENT_SECRET }}
          openai-model: ${{ vars.OPENAI_MODEL }}
          log-level: ${{ vars.LOG_LEVEL }}
