name: Tests

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install .NET runtime
      run: |
        # Install .NET runtime and Mono
        wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install -y dotnet-runtime-6.0 || true
        sudo apt-get install -y mono-runtime mono-devel || true
        
        # Set environment variables for pythonnet
        echo "PYTHONNET_RUNTIME=coreclr" >> $GITHUB_ENV
        
        # Verify installations
        dotnet --version || echo "dotnet not available"
        mono --version || echo "mono not available"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check test environment
      run: |
        python scripts/check_test_environment.py
    
    - name: Run unit tests
      run: |
        # Set environment variable to indicate we're in CI
        export CI=true
        python -m pytest tests/ -k "not test_integration" -v --tb=short
    
    - name: Run lint checks
      run: |
        # Install linting tools if they're not in requirements.txt
        pip install flake8 black isort || true
        # Run flake8 with our configuration
        flake8 src/ tests/ --config=.flake8
        echo "Linting completed successfully"

  integration-tests:
    runs-on: ubuntu-latest
    # Only run integration tests if secrets are available
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: unit-tests
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Check integration test configuration
      env:
        ENABLE_INTEGRATION_TESTS: ${{ secrets.ENABLE_INTEGRATION_TESTS }}
        TEST_XMLA_ENDPOINT: ${{ secrets.TEST_XMLA_ENDPOINT }}
        TEST_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}
        TEST_CLIENT_ID: ${{ secrets.TEST_CLIENT_ID }}
        TEST_CLIENT_SECRET: ${{ secrets.TEST_CLIENT_SECRET }}
        TEST_INITIAL_CATALOG: ${{ secrets.TEST_INITIAL_CATALOG }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "Integration tests enabled: ${ENABLE_INTEGRATION_TESTS:-false}"
        if [ "${ENABLE_INTEGRATION_TESTS}" = "true" ]; then
          echo "✅ Integration tests will run"
          echo "Test dataset: ${TEST_INITIAL_CATALOG:-Not configured}"
        else
          echo "ℹ️  Integration tests disabled or not configured"
        fi
    
    - name: Run integration tests
      if: env.ENABLE_INTEGRATION_TESTS == 'true'
      env:
        ENABLE_INTEGRATION_TESTS: ${{ secrets.ENABLE_INTEGRATION_TESTS }}
        TEST_XMLA_ENDPOINT: ${{ secrets.TEST_XMLA_ENDPOINT }}
        TEST_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}
        TEST_CLIENT_ID: ${{ secrets.TEST_CLIENT_ID }}
        TEST_CLIENT_SECRET: ${{ secrets.TEST_CLIENT_SECRET }}
        TEST_INITIAL_CATALOG: ${{ secrets.TEST_INITIAL_CATALOG }}
        TEST_EXPECTED_TABLE: ${{ secrets.TEST_EXPECTED_TABLE }}
        TEST_EXPECTED_COLUMN: ${{ secrets.TEST_EXPECTED_COLUMN }}
        TEST_DAX_QUERY: ${{ secrets.TEST_DAX_QUERY }}
        TEST_MIN_TABLES_COUNT: ${{ secrets.TEST_MIN_TABLES_COUNT }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        echo "🚀 Running integration tests..."
        python run_integration_tests.py --yes

  super-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort
    
    - name: Run Super-Linter
      uses: github/super-linter/slim@v4
      env:
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_PYTHON_FLAKE8: true
        VALIDATE_PYTHON_BLACK: true
        VALIDATE_PYTHON_ISORT: true
        VALIDATE_GITHUB_ACTIONS: true
        VALIDATE_YAML: true
        VALIDATE_MARKDOWN: true
        VALIDATE_DOCKERFILE: true
        VALIDATE_BASH: true
        VALIDATE_JSON: true
        VALIDATE_XML: true
        PYTHON_FLAKE8_CONFIG_FILE: .flake8
        PYTHON_BLACK_CONFIG_FILE: pyproject.toml
        PYTHON_ISORT_CONFIG_FILE: pyproject.toml
        FILTER_REGEX_EXCLUDE: '.*test_integration\.py$'

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security scan
      run: |
        echo "Security scan temporarily disabled"
        echo "TODO: Re-enable after fixing flake8 issues"
